import StyleDictionary from 'style-dictionary';
import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

const sd = new StyleDictionary({
  source: ['src/tokens/**/*.json'],
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: 'dist/styles/',
      files: [
        {
          destination: 'variables.css',
          format: 'css/variables',
          options: {
            outputReferences: true,
          },
        },
      ],
    },
    js: {
      transformGroup: 'js',
      buildPath: 'dist/',
      files: [
        {
          destination: 'tokens.js',
          format: 'javascript/es6',
        },
      ],
    },
    ts: {
      transformGroup: 'js',
      buildPath: 'dist/',
      files: [
        {
          destination: 'tokens.d.ts',
          format: 'typescript/es6-declarations',
        },
      ],
    },
  },
});

await sd.buildAllPlatforms();

// Generate Tailwind CSS v4 theme file
function generateTailwindTheme() {
  const variablesPath = join(__dirname, 'dist/styles/variables.css');
  const variablesContent = readFileSync(variablesPath, 'utf-8');

  // Extract CSS custom properties from :root
  const rootMatch = variablesContent.match(/:root\s*\{([^}]+)\}/);
  if (!rootMatch) return;

  const properties = rootMatch[1]
    .split(';')
    .map(line => line.trim())
    .filter(line => line.startsWith('--color-'))
    .map(line => {
      const [prop] = line.split(':');
      return prop.trim();
    });

  // Generate @theme block
  const themeProperties = properties
    .map(prop => `  ${prop}: var(${prop});`)
    .join('\n');

  const themeContent = `/**
 * Tailwind CSS v4 Theme - Auto-generated by Style Dictionary
 * Do not edit directly
 */

/* CSS Custom Properties */
${variablesContent}

/* Tailwind CSS v4 Theme Extension */
@theme {
${themeProperties}
}
`;

  writeFileSync(join(__dirname, 'dist/styles/theme.css'), themeContent);
  console.log('✔︎ dist/styles/theme.css');
}

generateTailwindTheme();

console.log('✅ Style Dictionary build complete!');
